# Generated by Django 4.0.6 on 2023-08-19 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='instituteData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=300)),
                ('state', models.CharField(max_length=100)),
                ('contactNumber1', models.CharField(max_length=10)),
                ('contactNumber2', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StudentsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('mother_name', models.CharField(blank=True, max_length=300, null=True)),
                ('father_name', models.CharField(blank=True, max_length=300, null=True)),
                ('class_std', models.CharField(blank=True, max_length=3, null=True)),
                ('schoolName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboardData.institutedata')),
            ],
        ),
    ]
