# Generated by Django 4.2.4 on 2023-08-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardData', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutedata',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentsdata',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
