# Generated by Django 4.0.6 on 2023-08-20 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardData', '0002_institutedata_email_studentsdata_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsdata',
            name='dateCreated',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 20, 20, 35, 9, 290144)),
        ),
        migrations.AddField(
            model_name='studentsdata',
            name='dateModified',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 20, 20, 35, 9, 290144)),
        ),
    ]
